@extends('layouts.master')
@section('title') Refund Policy | Online Books Review @endsection
@section('meta_description') Refund Policy @endsection
@section('meta_keyword') Refund Policy @endsection

@section('content')
    @include('includes.header')
<div class="thrv_paste_content thrv_wrapper tve_empty_dropzone" style="margin: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 18px; line-height: inherit; font-family: &quot;Source Sans Pro&quot;, arial; vertical-align: baseline; min-width: 20px; color: rgb(17, 17, 17);">
    <div class="thrv_wrapper thrv_heading" data-tag="h1" style="margin: 0px; padding: 1px; border: 0px; font: inherit; vertical-align: baseline; box-sizing: content-box; min-width: 20px;">
        <h1 class="tve_p_center rft" data-unit="px" style="margin-right: 0px; margin-left: 0px; padding: 0px; border: 0px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 35px; line-height: 50px; vertical-align: baseline; color: rgb(255, 146, 18); letter-spacing: -0.5px; text-align: center; margin-top: 0px !important; margin-bottom: 0px !important; font-weight: 600 !important; font-family: &quot;Source Sans Pro&quot;, &quot;trebuchet ms&quot; !important;">VFR &quot;Electric Fireplaces Market Growth&quot; Scholarship</h1>
    </div>
</div>

<div class="thrv_wrapper tve_image_caption img_style_lifted_style2" style="margin: 20px 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 18px; line-height: inherit; font-family: &quot;Source Sans Pro&quot;, arial; vertical-align: baseline; max-width: 100%; color: rgb(17, 17, 17); width: 1200px; box-sizing: border-box !important;"><span class="tve_image_frame" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; display: inline-block; max-width: 100%; position: relative; z-index: 1;"><img alt="Scholarship" class="tve_image" height="572" scale="2" src="https://i1.wp.com/www.onlinebooksreview.com/wp-content/uploads/2016/08/Untitled-1.jpg?zoom=2&amp;resize=1140%2C572" src-orig="https://i1.wp.com/www.onlinebooksreview.com/wp-content/uploads/2016/08/Untitled-1.jpg?resize=765%2C384" srcset="https://i1.wp.com/www.onlinebooksreview.com/wp-content/uploads/2016/08/Untitled-1.jpg?zoom=2&amp;resize=1140%2C572" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: top; max-width: 100%; height: auto; border-radius: 0px; box-shadow: none; display: block; width: 1200px;" width="1140" /></span></div>

<div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="margin: 0px; padding: 1px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 18px; line-height: inherit; font-family: &quot;Source Sans Pro&quot;, arial; vertical-align: baseline; min-width: 20px; color: rgb(17, 17, 17);">
    <p data-unit="px" style="font-size: inherit; margin: 0px 0px 28px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: 35px; font-family: inherit; vertical-align: baseline;"><font color="#e60e0e">Ventless Fireplace Review ( VFR)</font>&nbsp;is the Market Leader on reviewing different kinds of&nbsp;<a href="http://www.onlinebooksreview.com/" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; transition: all 0.4s ease 0s; color: rgb(17, 17, 17); outline: none !important;" target="_blank">ventless fireplace</a>&nbsp;including&nbsp;<a href="http://www.onlinebooksreview.com/2016/07/21/best-wall-mount-electric-fireplace-reviews/" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; transition: all 0.4s ease 0s; color: rgb(17, 17, 17); outline: none !important;" target="_blank">Electric Fireplace</a>,&nbsp;<a href="http://www.onlinebooksreview.com/2015/11/02/top-ventless-gel-fuel-fireplace-review/" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; transition: all 0.4s ease 0s; color: rgb(17, 17, 17); outline: none !important;" target="_blank">Gel Fireplace</a>,&nbsp;<a href="http://www.onlinebooksreview.com/2015/11/03/top-bio-ethanol-ventless-wall-mounted-fireplace-reviews/" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; transition: all 0.4s ease 0s; color: rgb(17, 17, 17); outline: none !important;">Bio Ethanol</a>&nbsp;,&nbsp;<a href="http://www.onlinebooksreview.com/category/ventless-gas-fireplace/" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; transition: all 0.4s ease 0s; color: rgb(17, 17, 17); outline: none !important;">Gas Fireplaces</a>.</p>

    <h2 class="tve_p_center" data-unit="px" style="margin: 25px 0px 30px; padding: 0px; border: 0px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 25px; line-height: 50px; vertical-align: baseline; text-align: center; background-color: rgb(244, 244, 244); font-weight: 600 !important; font-family: &quot;Source Sans Pro&quot;, &quot;trebuchet ms&quot; !important;">Background on Scholarship</h2>

    <p data-unit="px" style="font-size: inherit; margin: 0px 0px 28px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: 35px; font-family: inherit; vertical-align: baseline;">We know saving up for school can be tough. At VFR, we believe that scholarships can give ambitious students the opportunity to focus on his or her studies instead of worrying about the cost of books and tuition. With that little extra help, we believe you can achieve greatness. Ventless Fireplace Review is offering a $1,000 scholarship to enable one student chosen from all entries to pursue his or her education.</p>

    <h2 class="tve_p_center" data-unit="px" style="margin: 25px 0px 30px; padding: 0px; border: 0px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 25px; line-height: 50px; vertical-align: baseline; text-align: center; background-color: rgb(244, 244, 244); font-weight: 600 !important; font-family: &quot;Source Sans Pro&quot;, &quot;trebuchet ms&quot; !important;">Eligibility</h2>
</div>

<div class="thrv_wrapper thrv_bullets_shortcode thrv_text_element tve_empty_dropzone" style="margin: 0px; padding: 1px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 18px; line-height: inherit; font-family: &quot;Source Sans Pro&quot;, arial; vertical-align: baseline; min-width: 20px; color: rgb(17, 17, 17);">
    <ul class="tve_ul tve_ul1 tve_red" data-unit="px" style="margin: 0px 0px 15px 20px; padding-right: 0px; padding-left: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 1.4em; font-family: inherit; vertical-align: baseline; list-style: none;">
        <li style="margin: 0px 0px 10px 15px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 40px; font-family: inherit; vertical-align: baseline; list-style-type: disc; list-style-position: outside; list-style-image: url(&quot;/wp-content/plugins/thrive-visual-editor/editor/css/images/ul1_f_red.png&quot;) !important;">Students must be attending a two or four year university or college in the Fall of 2018.</li>
        <li style="margin: 0px 0px 10px 15px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 40px; font-family: inherit; vertical-align: baseline; list-style-type: disc; list-style-position: outside; list-style-image: url(&quot;/wp-content/plugins/thrive-visual-editor/editor/css/images/ul1_f_red.png&quot;) !important;"><a href="http://www.onlinebooksreview.com/" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; transition: all 0.4s ease 0s; color: rgb(44, 143, 244); outline: none !important;" target="_blank">www.onlinebooksreview.com</a>&nbsp;employees and their family members are not eligible to apply for this scholarship.</li>
        <li style="margin: 0px 0px 10px 15px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 40px; font-family: inherit; vertical-align: baseline; list-style-type: disc; list-style-position: outside; list-style-image: url(&quot;/wp-content/plugins/thrive-visual-editor/editor/css/images/ul1_f_red.png&quot;) !important;">Submission of application is regarded as acknowledgement and adherence to the following agreement guidelines below.</li>
    </ul>
</div>

<div class="thrv_wrapper thrv_heading" data-tag="h2" style="margin: 0px; padding: 1px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 18px; line-height: inherit; font-family: &quot;Source Sans Pro&quot;, arial; vertical-align: baseline; min-width: 20px; color: rgb(17, 17, 17);">
    <h2 class="tve_p_center" data-unit="px" style="margin: 25px 0px 30px; padding: 0px; border: 0px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 25px; line-height: 50px; vertical-align: baseline; text-align: center; background-color: rgb(244, 244, 244); font-weight: 600 !important; font-family: &quot;Source Sans Pro&quot;, &quot;trebuchet ms&quot; !important;">Application Requirements</h2>
</div>

<div class="thrv_wrapper thrv_bullets_shortcode thrv_text_element tve_empty_dropzone" style="margin: 0px; padding: 1px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 18px; line-height: inherit; font-family: &quot;Source Sans Pro&quot;, arial; vertical-align: baseline; min-width: 20px; color: rgb(17, 17, 17);">
    <ul class="tve_ul tve_ul2 tve_green" data-unit="px" style="margin-top: 0px; margin-right: 0px; padding-right: 0px; padding-left: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 1.4em; font-family: inherit; vertical-align: baseline; list-style: none; margin-bottom: 40px !important; margin-left: 100px !important;">
        <li style="margin: 0px 0px 10px 15px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 40px; font-family: inherit; vertical-align: baseline; list-style-type: disc; list-style-position: outside; list-style-image: url(&quot;/wp-content/plugins/thrive-visual-editor/editor/css/images/ul2_f_green.png&quot;) !important;">Each applicant must submit an essay of 700-800 words which includes</li>
        <li style="margin: 0px 0px 10px 15px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 40px; font-family: inherit; vertical-align: baseline; list-style-type: disc; list-style-position: outside; list-style-image: url(&quot;/wp-content/plugins/thrive-visual-editor/editor/css/images/ul2_f_green.png&quot;) !important;">Full name</li>
        <li style="margin: 0px 0px 10px 15px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 40px; font-family: inherit; vertical-align: baseline; list-style-type: disc; list-style-position: outside; list-style-image: url(&quot;/wp-content/plugins/thrive-visual-editor/editor/css/images/ul2_f_green.png&quot;) !important;">&acirc;&euro;&lsaquo;Mailing address and street address, if different</li>
        <li style="margin: 0px 0px 10px 15px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 40px; font-family: inherit; vertical-align: baseline; list-style-type: disc; list-style-position: outside; list-style-image: url(&quot;/wp-content/plugins/thrive-visual-editor/editor/css/images/ul2_f_green.png&quot;) !important;">&acirc;&euro;&lsaquo;Phone number</li>
        <li style="margin: 0px 0px 10px 15px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 40px; font-family: inherit; vertical-align: baseline; list-style-type: disc; list-style-position: outside; list-style-image: url(&quot;/wp-content/plugins/thrive-visual-editor/editor/css/images/ul2_f_green.png&quot;) !important;">&acirc;&euro;&lsaquo;Email address</li>
        <li style="margin: 0px 0px 10px 15px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 40px; font-family: inherit; vertical-align: baseline; list-style-type: disc; list-style-position: outside; list-style-image: url(&quot;/wp-content/plugins/thrive-visual-editor/editor/css/images/ul2_f_green.png&quot;) !important;">&acirc;&euro;&lsaquo;Area of study</li>
        <li style="margin: 0px 0px 10px 15px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 40px; font-family: inherit; vertical-align: baseline; list-style-type: disc; list-style-position: outside; list-style-image: url(&quot;/wp-content/plugins/thrive-visual-editor/editor/css/images/ul2_f_green.png&quot;) !important;">&acirc;&euro;&lsaquo;Name and mailing address of the university or college accepted into for the Fall of 2018</li>
        <li style="margin: 0px 0px 10px 15px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 40px; font-family: inherit; vertical-align: baseline; list-style-type: disc; list-style-position: outside; list-style-image: url(&quot;/wp-content/plugins/thrive-visual-editor/editor/css/images/ul2_f_green.png&quot;) !important;">&acirc;&euro;&lsaquo;Anticipated date of university or college graduation</li>
        <li style="margin: 0px 0px 10px 15px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 40px; font-family: inherit; vertical-align: baseline; list-style-type: disc; list-style-position: outside; list-style-image: url(&quot;/wp-content/plugins/thrive-visual-editor/editor/css/images/ul2_f_green.png&quot;) !important;">Your current GPA (high school or university/college)</li>
    </ul>
</div>

<div class="thrv_wrapper thrv_calltoaction_shortcode" data-tve-style="3" style="margin: 20px 0px; padding: 1px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 18px; line-height: inherit; font-family: &quot;Source Sans Pro&quot;, arial; vertical-align: baseline; min-width: 20px; color: rgb(17, 17, 17);">
    <div class="tve_ca tve_ca3 tve_red" style="margin-top: 0px !important; margin-right: auto; margin-bottom: 50px !important; margin-left: auto; padding: 45.5156px 45.5156px 10px; border: 2px solid rgb(205, 43, 31); font: inherit; vertical-align: baseline; box-sizing: content-box; position: relative; width: 967.297px; text-align: center;">
        <div class="tve_ca_o tve_empty_dropzone" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; box-sizing: content-box;">
            <div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="margin: 0px; padding: 1px; border: 0px; font: inherit; vertical-align: baseline; box-sizing: content-box; min-width: 20px;">
                <h2 class="tve_ca_heading" style="border: 0px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 25px; line-height: 30px; vertical-align: baseline; color: rgb(247, 91, 74); margin: 0px 0px 10px !important; padding: 0px !important; font-weight: 600 !important; font-family: &quot;Source Sans Pro&quot;, &quot;trebuchet ms&quot; !important;">Scholarship Topic</h2>

                <p style="font: inherit; margin: 0px !important; padding: 0px !important; border: 0px; vertical-align: baseline; color: rgb(136, 135, 135);">Write a short essay (700-800 words) describing &quot;Electric Fireplaces have Lapped the Field and are Growing at a Rapid Pace in the USA.&quot;</p>
            </div>
        </div>

        <div class="tve_ca_t" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; box-sizing: content-box; height: 40px;">
            <div class="tve_btn tve_btn2 tve_normalBtn tve_red" style="margin-right: auto; margin-left: auto; padding: 0px; border: 2px solid rgb(205, 43, 31); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 30px; line-height: 30px; font-family: inherit; vertical-align: baseline; display: inline-block; max-width: 100%; box-sizing: content-box; min-width: 250px; border-radius: 2px; background: rgb(233, 60, 49); bottom: -20px; position: relative; margin-top: 0px !important; margin-bottom: 50px !important;"><a class="tve_btnLink" href="https://www.onlinebooksreview.com/scholarship/" style="margin: 0px; padding: 20px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; transition: all 0.4s ease 0s; color: rgb(255, 255, 255); background: none; text-shadow: rgb(167, 12, 12) 0px 1px 0px; text-decoration-line: none !important; outline: none !important; display: block !important;"><span style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">Why?</span></a></div>
        </div>

        <div class="tve_corner" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; box-sizing: content-box;">&nbsp;</div>

        <div class="tve_clear" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; clear: both; box-sizing: content-box;">&nbsp;</div>
    </div>
</div>

<div class="thrv_wrapper thrv_contentbox_shortcode" data-tve-style="4" style="margin: 20px 0px; padding: 1px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 18px; line-height: inherit; font-family: &quot;Source Sans Pro&quot;, arial; vertical-align: baseline; position: relative; min-width: 20px; color: rgb(17, 17, 17);">
    <div class="tve_cb tve_cb4 tve_green" style="margin-top: 50px !important; margin-right: 0px; margin-bottom: 50px !important; margin-left: 0px; padding: 0px; border: 2px solid rgb(69, 191, 85); font: inherit; vertical-align: baseline; box-sizing: content-box; width: auto;">
        <div class="tve_hd" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; box-sizing: content-box;">&nbsp;</div>

        <div class="tve_cb_cnt tve_empty_dropzone" style="margin: 0px; padding: 20px; border: 0px; font: inherit; vertical-align: baseline; box-sizing: content-box;">
            <div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="margin: 0px; padding: 1px; border: 0px; font: inherit; vertical-align: baseline; box-sizing: content-box; min-width: 20px;">
                <h3 class="tve_p_center" style="margin-right: 0px; margin-left: 0px; padding: 0px; border: 0px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 21px; line-height: 25px; vertical-align: baseline; color: rgb(123, 197, 66); text-align: center; margin-top: 0px !important; margin-bottom: 0px !important; font-weight: 600 !important; font-family: &quot;Source Sans Pro&quot;, &quot;trebuchet ms&quot; !important;">Submission Must Be In Either PDF or Word Format</h3>

                <p style="font: inherit; margin-top: 10px !important; margin-right: 0px; margin-bottom: 0px !important; margin-left: 0px; padding: 0px; border: 0px; vertical-align: baseline;">When you will be done with these steps, email us at&nbsp;<font color="#e60e0e"><a href="mailto:scholarships@onlinebooksreview.com" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; transition: all 0.4s ease 0s; color: rgb(123, 197, 66); outline: none !important;" target="_blank">scholarships@onlinebooksreview.com</a></font>&nbsp;with all of the details listed below and attached Word document.</p>
            </div>
        </div>
    </div>
</div>

<div class="thrv_paste_content thrv_wrapper tve_empty_dropzone" style="margin-right: 0px; margin-left: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 18px; line-height: inherit; font-family: &quot;Source Sans Pro&quot;, arial; vertical-align: baseline; min-width: 20px; color: rgb(17, 17, 17); margin-top: 30px !important; margin-bottom: 40px !important;">
    <div class="thrv_wrapper thrv_text_element tve_empty_dropzone on_hover" style="margin: 0px; padding: 1px; border: 0px; font: inherit; vertical-align: baseline; box-sizing: content-box; min-width: 20px;">
        <p style="font: inherit; margin-top: 0px; margin-right: 0px; margin-bottom: 10px !important; margin-left: 0px; padding: 0px; border: 0px; vertical-align: baseline;"><span class="bold_text" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><font color="#ff9212">Application Submission Deadline:</font></span>&nbsp;April 31, 2018</p>

        <p style="font: inherit; margin-top: 0px; margin-right: 0px; margin-bottom: 10px !important; margin-left: 0px; padding: 0px; border: 0px; vertical-align: baseline;"><span class="bold_text" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><font color="#ff9212">Award:</font></span>&nbsp;One student will be awarded a $1,000 scholarship</p>

        <p style="font: inherit; margin-top: 0px; margin-right: 0px; margin-bottom: 10px !important; margin-left: 0px; padding: 0px; border: 0px; vertical-align: baseline;"><span class="bold_text" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><font color="#ff9212">Award Date:</font></span>&nbsp;May 20, 2018</p>

        <p style="font: inherit; margin: 0px 0px 28px; padding: 0px; border: 0px; vertical-align: baseline;"><span class="bold_text" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><font color="#ff9212">Agreement :</font></span>&nbsp;By submitting your article, you are giving us the permission to use it either for promotions and marketing purposes.</p>
    </div>
</div>

<div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="margin: 0px; padding: 1px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 18px; line-height: inherit; font-family: &quot;Source Sans Pro&quot;, arial; vertical-align: baseline; min-width: 20px; color: rgb(17, 17, 17);">
    <h1 class="tve_p_center" data-unit="px" style="margin: 12px 0px 15px; padding: 0px; border: 0px; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 28px; line-height: 80px; vertical-align: baseline; color: rgb(230, 14, 14); letter-spacing: -0.5px; text-align: center; background-color: rgb(193, 241, 255); font-weight: 600 !important; font-family: &quot;Source Sans Pro&quot;, &quot;trebuchet ms&quot; !important;"><font color="#151515">Total Submission Till Today :</font>&nbsp;29</h1>

    <p class="bold_text tve_p_center" style="font-size: 20px; margin-top: 30px !important; margin-right: 0px; margin-bottom: 30px !important; margin-left: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; text-align: center; color: rgb(21, 21, 21); background-color: rgb(224, 199, 249);">Valuable&nbsp;Posts from Our Experts Editors</p>

    <p style="font: inherit; margin: 0px 0px 28px; padding: 0px; border: 0px; vertical-align: baseline;">Read More About&nbsp;<a href="http://www.onlinebooksreview.com" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; transition: all 0.4s ease 0s; color: rgb(44, 143, 244); outline: none !important;" target="_blank">Wall Mount Electric Fireplace</a></p>

</div>
    @include('includes.footer')
@endsection
